Azure/Bridge-To-Kubernetes

src/.vscode/launch.json
src/.vscode/tasks.json
src/library/Connect/KubernetesRemoteEnvironmentManager.cs

Upgrade to Kubernetes Client C# library 7.2.19 instroduced JSON regression because new version switches from using newtonsoft to system.text.json, but system.text.json does not support JsonPatch. Related: https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-6.0#add-support-for-json-patch-when-using-systemtextjson and https://github.com/dotnet/aspnetcore/issues/14035

Implement workaround to json regression 

---

src/dsc/Remoting/RemotingHelper.cs

In some occasions we see token hang up error when disconnecting bridge debugger. This is caused because on disconnect cancellation signal to tear down server is sent immediately, sometime before response is sent to the client. Adding a delay on cancellation token so http server has enough time to send ok before being teared down.

delay cancelation token by one second

---

src/library.tests/LocalEnvironmentManagerTests.cs
src/library/Connect/ILocalEnvironmentManager.cs
src/library/Connect/LocalEnvironmentManager.cs

Background: Managed Identity feature of bridge to kubernetes was not working when user ran under useKubernetesServiceEnvironmentVariables. Bridge adds MSI_ENDPOINT environment variable as a DNS name for the "fake" manage identity service bridge starts (http://managedidentityforbridgetokubernetes/metadata/identity/oauth2/token). When user runs bridge as useKubernetesServiceEnvironmentVariables we dont have access to add entry in host files and thus when MSI library tried to hit that endpoint there was a DNS resolution error.  
With this fix we make sure that when user runs as useKubernetesServiceEnvironmentVariables we add MSI_ENDPOINT using IP:Port instead of DNS name. Something like http://127.0.0.1:5050/metadata/identity/oauth2/token
This PR also adds UT coverage for that function. …

Fix Managed Identity when with useKubernetesServiceEnvironmentVariables

---

src/devhostagent/PortForward/ServicePortForwardConnector.cs
src/devhostagent/readme.md

Current Managed Identity workflow works with C# MI library, but it was erroring out when MI was being used from Go library. Request was being updated per below, **this** was being added in the wrong place. This PR simplifies and fixes the function that updates the request before sending to real manage identity. 
2022-11-04T00:47:46.2175539Z | RemoteAgent | TRACE | ManagedIdentity :  Original data : GET /metadata/identity/oauth2/token?api-version=2017-09-01&mi_res_id=%2Fsubscriptions%2F4be8920b-2978-43d7-ab14-04d8549c1d05%2FresourceGroups%2FAKSE2EInfra%2Fproviders%2FMicrosoft.ManagedIdentity%2FuserAssignedIdentities%2\nAccept-Encoding: gzip (amd64-linux) go-autorest/adal/v1.0.0.1
2022-11-04T00:47:46.2178054Z | RemoteAgent | TRACE | ManagedIdentity :  Sending data : **Metadata: …

Address Managed Identity workflow for Go library

---

src/library.tests/PortMappingManagerTest.cs
src/library.tests/WorkloadInformationProviderTests.cs
src/library/Connect/WorkloadInformationProvider.cs

Our code assumes that every endpoint for a headless service will have subsets associated with it. This causes crash if customer ever tries to connect Bridge to a cluster that has a headless service with an endpoint that does not have subsets defined.

Fix Connect crash when headless service has endpoint with empty subsets

---

src/.vscode/launch.json
src/.vscode/tasks.json
src/library.tests/LocalEnvironmentManagerTests.cs
src/library/Connect/LocalEnvironmentManager.cs

When user uses useKubernetesServiceEnvironmentVariables, our code replaces IP associated with KUBERNETES_SERVICE_HOST env variable value with full host name. However, it was checking for ServiceName == KUBERNETES, but the code uses dnsName as service name and if the service being debugged is running in namepace outside default (where kubernestes service runs), the check wouldnt work.
This PR fixes this check, adds UTs coverage and adds task.json and launch.json updates so we can use VSCode debugger when running UTs.

Update how service name when adding environment variables

---

azure-pipelines.yml

This PR is to update static variables in the pipeline to parameters so that when a build is triggered, a value can be selected manually.
Refer below screenshot: for Dev purposes sign type can be test but for production releases it can be real with M2 approval.

Update pipelines to use parameters for signing type and telemetry type as selection by user

---

azure-pipelines.yml

[This commit](https://github.com/Azure/Bridge-To-Kubernetes/commit/12c88bfe897402d3ea2dd6438b3b7861eb9d4871#diff-7915b9b726a397ae7ba6af7b9703633d21c031ebf21682f3ee7e6a4ec52837a5) removed configuration from being passed to donet pack command. This leads to nuget version to be wrong (version-cloudttest instead of just version). Which leads to VS extension to not be able to find the nuget package. This PR adds build configuration.

Fix dotnet pack to include build configuration

---

src/library/Client/ManagementClients/KubernetesManagementClient.cs

When investigating [this issue](https://github.com/Azure/Bridge-To-Kubernetes/issues/158) I noticed that result of refreshcredentials was only set to false because we were missing a set succeeded on the perflogger, but it was exiting on the happy path.

RefreshCredentialsAsync was missing a SetSucceeded for perf logger

---

azure-pipelines.yml

Currently signing verification happens on release nuget package pipeline. This change aim to add this check sooner on the release process.

Add signing validation to our official build pipeline

---

samples/todo-app/database-api/databaseApi.csproj

This PR is to fix the deployment issue for database api in samples/todo/database-api due to dotnet version mismatch between csproj and docker file.

Updating database api project to dotnet 6

---

src/library.tests/WorkloadInformationProviderTests.cs
src/library/Connect/WorkloadInformationProvider.cs

This Pr address incorrect assumption done on [this PR](https://github.com/Azure/Bridge-To-Kubernetes/pull/78/files#diff-c415242ad7d5ebbf107822a6ba3ee5f15ccbbc0220f5948047db4f78bbe1add5). If address did not have hostname it was being skipped, but kubernetes still adds dns for it, it uses the endpoint dns if hostname not specified.
UTs have been updated accordingly.  Fixed also verified against set up that reproduced the issue.
Address #167 and #155.

Use endpoint dns if hostname not specified for the address

---

.gitignore

This PR adds launchSettings.json to the .gitignore file so it does not automaticly gets added to git.
Closes #244

Added launchSettings.json to .gitignore

---

CHANGELOG.md

This PR is to update changelog to prepare for 04.25 release and below are changes that are rolled out in this release. Thank you. 
- [Enable auto review by chatgpt](https://github.com/Azure/Bridge-To-Kubernetes/pull/232)
- [Update base images to microsoft mariner images](https://github.com/Azure/Bridge-To-Kubernetes/pull/175)
- [Add new editor config files](https://github.com/Azure/Bridge-To-Kubernetes/pull/230)
- [Added SupportedOSPlatformGuard and new improved operating system identification](https://github.com/Azure/Bridge-To-Kubernetes/pull/213)
- [Remove root permissions for creating symlink in user's local bin folder](https://github.com/Azure/Bridge-To-Kubernetes/pull/216)
- [Modified method to have one set of env variables and added …

update change log for release 04.25

---

src/common/Json/JsonHelpers.cs

This PR fixes three occurences where nullable reference types where being used but the project had not enabled this feature.
Fixes #252

Fixes warnings for nullable reference types being used

---

src/common.tests/FixedSizeStringBuilderTests.cs
src/library.tests/PortMappingManagerTest.cs
src/library.tests/RemoteContainerConnectionDetailsResolverTests.cs

This PR fixes some tests that had swaped the actual argument with the expected argument.
It also optimizes a test by using Assert.DoesNotContains instead of multiple checks.
This change removes 4 warnings.
Fixed #254

Fixed swaped arguments

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

This PR is to update bug/issue/feature request templates with labels and include logs location so that users can include the logs from their dev machines for faster triaging.

update issue template with b2k logs location 

---

src/common/IP/IPManager.cs

This PR is to fix https://github.com/Azure/Bridge-To-Kubernetes/issues/223.
- This code adds a wait time of 30 seconds for iptables operation which would wait for adding iptables rules for redirection when xtables are locked by another process. In most cases this will not happen. Thank you.

Iptables wait option

---

README.md

This PR includes codeQL badge status to readme.

Include CodeQL badge status

---

src/library/Extensions/V1ContainerExtensions.cs

See also https://github.com/Azure/Bridge-To-Kubernetes/issues/292
This PR allows Jaeger side car support by bridge.

Added jaeger-agent as known sidecar

---

scripts/install.sh

This PR is to update install script to download and use dotnet 7.0. Made a small improvement to install aspnetcore-runtime even if dotnet sdk and dotnetruntime exists because bridge requires aspnetcore-runtime.
```
curl -fsSL https://raw.githubusercontent.com/hsubramanianaks/Bridge-To-Kubernetes/install-script-dotnet7/scripts/install.sh | bash
```
**Testing screenshots:**
**Ubuntu 20.04:**
**Windows - Gitbash**
**Macos - amd64**
**Macos-arm64**

Install script - update to dotnet 7.0

---

.github/workflows/live-test.yml
.github/workflows/ok-to-test.yml
scripts/live_test.sh
scripts/verify.sh

See https://github.com/Azure/Bridge-To-Kubernetes/issues/140
This PR: 
Adds live test for windows and mac, workflow will create an AKS cluster to run the test.
No changes to test for linux
Now the tests for all 3 platforms will be triggered by slash command and `sha` input like `/ok-to-test sha=1234567` in PR comment
A latest run in my fork: https://github.com/cxznmhdcxz/Bridge-To-Kubernetes/actions/runs/5798264426

add live-test dispatch workflow for windows and mac

---

samples/managed-identity/KubernetesLocalProcessConfig.yaml

This PR is to update managed identity client id to right one since manual testing was failing and previous PR missed updating this.

update managed identity clientid to latest

---

src/library.tests/RemoteContainerConnectionDetailsResolverTests.cs
src/library/Extensions/V1PodExtensions.cs
src/library/Utilities/RemoteContainerConnectionDetailsResolver.cs

This PR is to fix #267. 
Root cause was if a user cluster contains multiple pods with same/similar name but different kind like pod-a is replicaset and pod-a-job is job, code is failing to recognize this and throws errors.

Filter pods which are not replicatset or statefulset

---

samples/ingress/frontend/components/TodoFooter.js
samples/ingress/frontend/package-lock.json
samples/ingress/frontend/package.json
samples/ingress/frontend/pages/stats.js
samples/todo-app/frontend/package-lock.json
samples/todo-app/frontend/package.json

based on #324 and #325
fix package version conflict: changed react@17.0.2 -> react@18.2.0
fix component compile error: upgrade next.js version

fix package version for todo-app/frontend and ingress/frontend

---

CHANGELOG.md

This PR is to create change log for November release.

Add change log for Nov release

---

azure-pipelines.yml
src/library/EndpointManagement/EndpointManagementClient.cs

This PR fixes 
- M1 mac issue - https://github.com/Azure/Bridge-To-Kubernetes/issues/345
- enhancing exception message with error code to known the actual error code. 
this change is to fix the user's issue. There will be a follow up PR to enhance or make the build scripts more readable and maintainable.

Mac arm64 build

---

src/library.tests/LocalEnvironmentManagerTests.cs
src/library/Connect/LocalEnvironmentManager.cs

Fix https://github.com/Azure/Bridge-To-Kubernetes/issues/234
This PR fixes Index out of bound when user's namespace contains UDP services without ports.

Skip endpoint without ports in LocalEnvironmentManager

---

azure-pipelines.yml

This PR is removing the step which does dotnet pack for win-arm64 due to vs extension is not ready to consume these arm64 binaries.

removing dotnet pack for win-arm64

---

.github/workflows/acr-build-publish.yml

This branch PR fixes the acr build and push using different 1es pools for development vs prod registries for b2k. 
example run for staging - https://github.com/Azure/Bridge-To-Kubernetes/actions/runs/8088192134
development - https://github.com/Azure/Bridge-To-Kubernetes/actions/runs/8088254811
prod - https://github.com/Azure/Bridge-To-Kubernetes/actions/runs/8072443965/job/22054200309

update 1es pool names
