- CODEOWNERS
Reverts Azure/Bridge-To-Kubernetes#7
> Revert "Adding Tatsat to codeowners"

- .github/workflows/codeql-analysis.yml
Add code ql scanning for CLI to avoid security issues.
> code ql feature for C sharp

- .github/workflows/binaries-analysis.yml
Hello All, 
1. This PR is a github action to scan generated binaries for bridge CLI using binskim tool and fail if any vulnerabilities is found.
2. This is required as part of SDL (Secure Development Lifecycle) process.
3. Here is the work items linked to it - https://msazure.visualstudio.com/CloudNativeCompute/_workitems/edit/15304625
Thank you for looking into this PR.
> Binaries analysis using Binskim tool for SDL

- samples/ingress/stats-api/package-lock.json
- samples/ingress/stats-worker/package-lock.json
- samples/ingress/stats-worker/package.json
Same npm updates for regular todo app need to be applied to ingress version of the todo app.
> Fix dependentbot alerts on ingress todo app sample

- tests/manual/BridgeToKubernetes.md
Steps to config debug where outdated
> update step to debug configures

- tests/manual/BridgeToKubernetes.md
Steps to test mount volume feature where outdated and not working. Updating them with working ones.
> Update steps to test mount volume feature

- src/routingmanager/RoutingManagerApp.cs
- tests/manual/BridgeToKubernetes.md
This PR is to fix the port issue when port.number is provided for ingress and debugging via B2K fails for isolation mode.
Here are the issues
https://github.com/Azure/Bridge-To-Kubernetes/issues/49
https://github.com/Azure/Bridge-To-Kubernetes/issues/25
> Bug fix for Ingress port Issue

- README.md
Signed-off-by: Sajay Antony <sajaya@microsoft.com>
> docs: fix vs-code link and use non-regional links

- samples/todo-app/frontend/components/TodoApp.js
- samples/todo-app/frontend/pages/stats.js
Related issue: https://github.com/expressjs/express/issues/2736
Express change log: https://expressjs.com/en/changelog/4x.html version 4.17.2 is the one that introduced the change.
> Fixing regression introduced by express upgrade

- README.md
This PR is to update build status badge to correct pipeline after dotnet 6 upgrade.
> Update Build status badge

- build-pipelines-PR.yml
Creating build pipeline for PRs that does not have signing.
> Set up build pipeline for PRs

- src/client.signproj
nuget push was failing on signature verification due to this new assembly not being signed.
> Update client.signproj to sign systemtextjsonpatch

- azure-pipelines.yml
- build-pipelines-PR.yml
This PR is to clean up PR build pipelines and make them simple.
> Cleanup PR build pipelines

- CHANGELOG.md
Change log update for 032923 release for B2K CLI.
> change log update for 032923 release

- .github/workflows/chatgpt-review.yml
This PR enables the auto review of the PR(s) the only caveat is that if description in the PR will be too long the token issues of chatgpt will kick in which could error out the workflow but beside that this workflow should suffice the first hand auto review.
fyi and thanks @hsubramanianaks  - we can chat real quick abut this and might be get a OpenAI token for this setup.  Thanks heaps, ❤️☕️🥷
> Enable auto review using chatgpt.

- src/common/EndpointManagement/IHostsFileManager.cs
- src/common/Logging/LoggingUtils.cs
- src/common/Socket/ISocket.cs
This PR fixes the invalid xml documentation tags so the warnings from building the projects no longer occures. 
Fixes #256
> Fixes invalid xml documentation tags

- src/library/Client/ManagementClients/KubeConfigManagementClient.cs
This PR fixes a problem with a exception that was not rethrown correctly.
Now the stacktrace will be correct when it gets logged to file.
Fixed #260
> Fixed exception rethrow

- README.md
This came out from conversation with @hsubramanianaks 🙏☕️ please take a look if this is correct and we can update the readme. thanks.
> Remove inaccurate statement.

- samples/ingress/frontend/package-lock.json
- samples/ingress/frontend/package.json
- samples/ingress/frontend/server.js
- samples/todo-app/frontend/package-lock.json
- samples/todo-app/frontend/package.json
This PR removes deprecated dependencies from samples folder.
> Remove deprecated dependencies from samples

- CHANGELOG.md
This PR is to update change log for July release.
> add changelog for July release

- .github/workflows/acr-build-publish.yml
This PR is to fix the routing manager tag issue causing testing for ARM clusters fail. @cxznmhdcxz FYIP.
> Fix acr pipeline

- CHANGELOG.md
This PR is to update change log for Jan 2024 release which contains fixes for m1 mac arm64 issue and dependent bot alerts.
> Jan 2024 release

- .github/dependabot.yml
@hsubramanianaks for weekly update PR please.
> Run weekly.

- src/common.tests/common.tests.csproj
- src/devhostAgent.restorationjob.tests/devhostAgent.restorationjob.tests.csproj
- src/dsc.tests/dsc.tests.csproj
- src/endpointmanager.tests/endpointmanager.tests.csproj
- src/library.tests/library.tests.csproj
- src/testhelpers/testhelpers.csproj
This PR combination of all these PR's 
#460 
#508 
#529 
#538 
#543
> bump fake it easy dependency

- src/common.tests/common.tests.csproj
- src/devhostAgent.restorationjob.tests/devhostAgent.restorationjob.tests.csproj
- src/dsc.tests/dsc.tests.csproj
- src/endpointmanager.tests/endpointmanager.tests.csproj
- src/library.tests/library.tests.csproj
- src/routingmanager.tests/routingmanager.tests.csproj
- src/testhelpers/testhelpers.csproj
This PR handles the following PR's
#576 
#590 
#593 
#594 
#598 
#599 
#600 
#601
> bump xunit
